Homepage styling options
daattali/beautiful-jekyll pull request #1262
Opened 2023-12-31 11:24 UTC by vakesz

Issue reference: https://github.com/daattali/beautiful-jekyll/issues/1192

2024-01-04 07:13 UTC, daattali requested changes

2024-01-04 07:13 UTC, daattali commented on Gemfile
> +install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
Can you put this in a separate PR, since it's unrelated to this issue?

2024-01-04 07:13 UTC, daattali commented on _config.yml
> +post_header_style: "square"
After seeing this parameter for the first time in months, I realize that it's really badly named. "post_header_style" doesn't give a clue what this is actually doing. Maybe `post_preview_image` instead, or something similar

2024-01-04 07:13 UTC, daattali commented on _includes/social-networks-links.html
> +        <i class="fab fa-x-twitter fa-stack-1x fa-inverse"></i>
This is unrelated, should be a separate PR

2024-01-04 07:13 UTC, daattali commented on _includes/social-share.html
> +      <span class="fab fa-fw fa-x-twitter" aria-hidden="true"></span>
Not part of this PR

2024-01-04 07:13 UTC, daattali commented on _layouts/base.html
> +  - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
You know the drill :p

2024-01-04 07:13 UTC, daattali commented on _layouts/home.html
> +      {% if site.post_header_style == "wide" %}
Shouldn't this still be wrapped in the `if thumbnail !- ""`? Because if there's no thumbnail, then this should not be run?

2024-01-04 07:13 UTC, daattali commented on _layouts/home.html
> +      {% if thumbnail != "" and site.post_header_style == "none" %}
Maybe where `thumbnail` gets defined above, there should be a check to see if the user is choosing to not show image preview. If the user chooses "none", then set `thumbnail` to be empty

2024-01-04 07:13 UTC, daattali commented
Thanks for the initiative. I made some comments

2024-03-13 05:15 UTC, daattali commented
@vakesz do you want to finish this PR?

2024-03-22 05:30 UTC, daattali commented
@vakesz ping :)

2024-04-16 14:09 UTC, daattali commented
@vakesz would you like to finish this PR?

2024-04-16 14:20 UTC, closed without merging

2024-04-16 14:23 UTC, vakesz commented
Will reopen if I'll have more time. Even though all changes are relatively small I can't put time into this topic. Sorry though.