Add a title_on_all_pages site optoin
daattali/beautiful-jekyll pull request #1272
Opened 2024-01-12 18:22 UTC by pedantic-git

This PR adds a site option called `title_on_all_pages` - it adds the `site.title` to the end of all page titles (separated by `|`), unless the `site.title` and `title` are the same string (usually on home pages).

This still contains my commit from #1270 but if you like the idea, and the variable name, I'll tidy it up and remove that commit before you accept it. No worries if you don't want this option in your theme!

2024-01-18 06:23 UTC, daattali requested changes
Good idea, I like it. Please remove the changes related to the jekyll version

2024-01-18 06:23 UTC, daattali commented on _includes/head.html
> +    {%- if site.title_on_all_pages and (site.title != pagetitle) -%}
Should also check here that `site.title` exists. Someone who doesn't use this config.yml file might not have a title parameter.

2024-01-18 06:23 UTC, daattali commented on _config.yml
> +title_on_all_pages: false
Naming convention for field names in this file is `title-on-all-pages`

2024-01-20 08:10 UTC, PublisherApplications reviewed
I approved these changes.

2024-01-20 08:10 UTC, PublisherApplications commented on Gemfile
> -gemspec
good

2024-01-20 08:10 UTC, PublisherApplications commented on Gemfile
> +gem 'jekyll', '~> 3.9.3'
good

2024-01-20 08:10 UTC, PublisherApplications commented on _config.yml
> +title_on_all_pages: false
yea

2024-01-20 08:10 UTC, PublisherApplications commented on _config.yml
> +# Show the site title in the <title> of all pages in addition to the page title
You sure remove these comments.

2024-01-20 08:10 UTC, PublisherApplications commented on _includes/head.html
> +  {% capture pagetitle %}
Thank you for changing this.

2024-01-20 08:10 UTC, PublisherApplications commented on _includes/head.html
> +    {%- if site.title_on_all_pages and (site.title != pagetitle) -%}
Thank you for reviewing this..

2024-01-20 08:10 UTC, PublisherApplications commented on beautiful-jekyll-theme.gemspec
> +  spec.add_runtime_dependency "jekyll", ">= 3.9.3"
Thank you for changing this.

2024-01-20 08:10 UTC, PublisherApplications commented on beautiful-jekyll-theme.gemspec
> -  spec.add_runtime_dependency "jekyll", "~> 3.9.3"
Thank you for changing this.

2024-01-20 12:03 UTC, pedantic-git commented
Hi @daattali - thank you for your support and your review! I've made those requested changes now and unmarked this as draft.

I hope you don't mind - I also changed site.title in your example app to match the page.title of the homepage (it was only a case difference) - that makes it easier for people to see how this works.

CI is still passing in my env so hopefully it should be good to go!

2024-01-20 14:17 UTC, hami22123 commented
Thank you very much for your response in such a short time, and also thank
you for giving value to your audience.

در تاریخ شنبه ۲۰ ژانویهٔ ۲۰۲۴،‏ ۱۵:۳۳ Quinn ***@***.***> نوشت:

> Hi @daattali <https://github.com/daattali> - thank you for your support
> and your review! I've made those requested changes now and unmarked this as
> draft.
>
> I hope you don't mind - I also changed site.title in your example app to
> match the page.title of the homepage (it was only a case difference) - that
> makes it easier for people to see how this works.
>
> CI is still passing in my env so hopefully it should be good to go!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/daattali/beautiful-jekyll/pull/1272#issuecomment-1902077107>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUN32KHXTIT6KMLBFMK3MGDYPOXBVAVCNFSM6AAAAABBYQ6EG2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBSGA3TOMJQG4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-01-20 14:25 UTC, homayouniarieed commented
Hello, I am amazed and surprised that you published the answer to my email on github with such a high speed, it was great.

2024-01-20 22:27 UTC, daattali commented
Looks good, thanks! I made small changes and added to changelog.
I'm not sure why this PR was targeted by so much spam...

2024-01-20 22:27 UTC, merged